### ISSUE TITLE
Can't edit and see Jetton's image

### ISSUE THREAD

**Issue by BlackFQ** [ton-defi-org/jetton-deployer-contracts#21]
https://jetton.live/jetton/EQCc8dneil4jiJ2sgHi_3lYhVvtGxWjVPYMQFMdj2YxX5Jye

**Comment by shaharyakir** [comment]
You will be able to view the jetton now, it was deployed with faulty serialization, but you as the admin can fix it.
Editing the image, however, is not supported.
