### ISSUE TITLE
Token metadata requires fix . Dont have pending notification on my Tonhub app, to edit the token

### ISSUE THREAD

**Issue by BlackFQ** [ton-defi-org/jetton-deployer-contracts#26]
https://jetton.live/jetton/EQCkR51Sf3RRqSX10o8-oZaxMhzODQp4y7sbydQ8CjRfLTc5

Cant recieve any query or noti in app for editing this token

**Comment by shaharyakir** [comment]
Can you clarify what do you mean by editing the token?
